export const hyroxYellow = '#ffed00';
export const hyroxYellowDark1 = '#e5d600';
export const hyroxYellowDark2 = '#dfbd00';
export const hyroxBlack = '#000000';
export const hyroxWhite = '#ffffff';

export const HYROX_THEME = {
  focusOutlineColor: hyroxWhite,
  textLinkColor: hyroxYellow,
  textLinkColorHover: hyroxYellowDark1,
  textLinkColorActive: hyroxYellowDark2,
  textLinkColorDarkMode: hyroxYellow,
  textLinkColorHoverDarkMode: hyroxYellowDark1,
  textLinkColorActiveDarkMode: hyroxYellowDark2,
  checkboxTickColor: hyroxYellow,
  checkboxTickColorDarkMode: hyroxYellow,
  progressBarColor: hyroxYellow,
  progressBarColorDarkMode: hyroxYellow,
  quoteBarColor: hyroxYellowDark1,
  quoteBarColorDarkMode: hyroxYellowDark1,
  buttonPrimaryBackgroundColor: hyroxYellow,
  buttonPrimaryBackgroundColorDarkMode: hyroxYellow,
  buttonPrimaryBackgroundColorHover: hyroxYellowDark1,
  buttonPrimaryBackgroundColorHoverDarkMode: hyroxYellowDark1,
  buttonPrimaryBackgroundColorActive: hyroxYellowDark2,
  buttonPrimaryBackgroundColorActiveDarkMode: hyroxYellowDark2,
  buttonPrimaryForegroundColor: hyroxBlack,
  buttonPrimaryForegroundColorDarkMode: hyroxBlack,
  buttonPrimaryForegroundColorHover: hyroxBlack,
  buttonPrimaryForegroundColorHoverDarkMode: hyroxBlack,
  buttonPrimaryForegroundColorActive: hyroxBlack,
  buttonPrimaryForegroundColorActiveDarkMode: hyroxBlack,
  buttonDestructiveBackgroundColor: hyroxBlack,
  buttonDestructiveBackgroundColorDarkMode: null,
  buttonDestructiveForegroundColor: hyroxBlack,
  buttonDestructiveForegroundColorDarkMode: hyroxBlack,
  buttonDestructiveForegroundColorHover: hyroxBlack,
  buttonDestructiveForegroundColorHoverDarkMode: hyroxBlack,
  buttonBouncyBackgroundColorHover: hyroxYellow,
  buttonBouncyBackgroundColorHoverDarkMode: hyroxYellow,
  buttonBouncyBackgroundColorActive: hyroxYellowDark1,
  buttonBouncyBackgroundColorActiveDarkMode: hyroxYellowDark1,
  buttonBouncyBackgroundColorDarkMode: null,
  buttonBouncyForegroundColor: hyroxWhite,
  buttonBouncyForegroundColorDarkMode: hyroxWhite,
  buttonBouncyForegroundColorHover: hyroxBlack,
  buttonBouncyForegroundColorHoverDarkMode: hyroxBlack,
  buttonBouncyForegroundColorActive: hyroxBlack,
  buttonBouncyForegroundColorActiveDarkMode: hyroxBlack,
  cardHighlightColor: null,
  cardHighlightColorDarkMode: null,
  cardHoverForegroundColor: null,
  cardHoverForegroundColorDarkMode: null,
  cardHoverForegroundColorHover: null,
  cardHoverForegroundColorHoverDarkMode: null,
};
