#! /bin/bash

# Example team
curl 'http://localhost:3000/api/team/create' -X POST -H 'Content-Type: application/json' --data-raw \
'{"requestedId":"test-team"}'


# Athlete preferences
curl 'http://localhost:3000/api/athlete/update/tf-webhook' -X POST -H 'Content-Type: application/json' --data-raw \
'{ "form_response": { "hidden": { "teamid": "test-team", "athleteid": "athlete-1" }, "definition": { "fields": [ { "id": "athlete-name", "ref": "athlete-name" }, { "id": "ski-erg", "ref": "ski-erg" }, { "id": "sled-push", "ref": "sled-push" }, { "id": "sled-pull", "ref": "sled-pull" }, { "id": "burpee-broad-jumps", "ref": "burpee-broad-jumps" }, { "id": "rowing", "ref": "rowing" }, { "id": "farmers-carry", "ref": "farmers-carry" }, { "id": "sandbag-lunges", "ref": "sandbag-lunges" }, { "id": "wall-balls", "ref": "wall-balls" } ] }, "answers": [ { "field": { "id": "athlete-name" }, "text": "Fred" }, { "field": { "id": "ski-erg" }, "number": 4 }, { "field": { "id": "sled-push" }, "number": 7 }, { "field": { "id": "sled-pull" }, "number": 2 }, { "field": { "id": "burpee-broad-jumps" }, "number": 7 }, { "field": { "id": "rowing" }, "number": 6 }, { "field": { "id": "farmers-carry" }, "number": 1 }, { "field": { "id": "sandbag-lunges" }, "number": 10 }, { "field": { "id": "wall-balls" }, "number": 3 } ] } } '

curl 'http://localhost:3000/api/athlete/update/tf-webhook' -X POST -H 'Content-Type: application/json' --data-raw \
'{ "form_response": { "hidden": { "teamid": "test-team", "athleteid": "athlete-2" }, "definition": { "fields": [ { "id": "athlete-name", "ref": "athlete-name" }, { "id": "ski-erg", "ref": "ski-erg" }, { "id": "sled-push", "ref": "sled-push" }, { "id": "sled-pull", "ref": "sled-pull" }, { "id": "burpee-broad-jumps", "ref": "burpee-broad-jumps" }, { "id": "rowing", "ref": "rowing" }, { "id": "farmers-carry", "ref": "farmers-carry" }, { "id": "sandbag-lunges", "ref": "sandbag-lunges" }, { "id": "wall-balls", "ref": "wall-balls" } ] }, "answers": [ { "field": { "id": "athlete-name" }, "text": "John" }, { "field": { "id": "ski-erg" }, "number": 4 }, { "field": { "id": "sled-push" }, "number": 7 }, { "field": { "id": "sled-pull" }, "number": 2 }, { "field": { "id": "burpee-broad-jumps" }, "number": 7 }, { "field": { "id": "rowing" }, "number": 6 }, { "field": { "id": "farmers-carry" }, "number": 1 }, { "field": { "id": "sandbag-lunges" }, "number": 10 }, { "field": { "id": "wall-balls" }, "number": 3 } ] } } '

curl 'http://localhost:3000/api/athlete/update/tf-webhook' -X POST -H 'Content-Type: application/json' --data-raw \
'{ "form_response": { "hidden": { "teamid": "test-team", "athleteid": "athlete-3" }, "definition": { "fields": [ { "id": "athlete-name", "ref": "athlete-name" }, { "id": "ski-erg", "ref": "ski-erg" }, { "id": "sled-push", "ref": "sled-push" }, { "id": "sled-pull", "ref": "sled-pull" }, { "id": "burpee-broad-jumps", "ref": "burpee-broad-jumps" }, { "id": "rowing", "ref": "rowing" }, { "id": "farmers-carry", "ref": "farmers-carry" }, { "id": "sandbag-lunges", "ref": "sandbag-lunges" }, { "id": "wall-balls", "ref": "wall-balls" } ] }, "answers": [ { "field": { "id": "athlete-name" }, "text": "Andrew" }, { "field": { "id": "ski-erg" }, "number": 4 }, { "field": { "id": "sled-push" }, "number": 7 }, { "field": { "id": "sled-pull" }, "number": 2 }, { "field": { "id": "burpee-broad-jumps" }, "number": 7 }, { "field": { "id": "rowing" }, "number": 6 }, { "field": { "id": "farmers-carry" }, "number": 1 }, { "field": { "id": "sandbag-lunges" }, "number": 10 }, { "field": { "id": "wall-balls" }, "number": 3 } ] } } '

curl 'http://localhost:3000/api/athlete/update/tf-webhook' -X POST -H 'Content-Type: application/json' --data-raw \
'{ "form_response": { "hidden": { "teamid": "test-team", "athleteid": "athlete-4" }, "definition": { "fields": [ { "id": "athlete-name", "ref": "athlete-name" }, { "id": "ski-erg", "ref": "ski-erg" }, { "id": "sled-push", "ref": "sled-push" }, { "id": "sled-pull", "ref": "sled-pull" }, { "id": "burpee-broad-jumps", "ref": "burpee-broad-jumps" }, { "id": "rowing", "ref": "rowing" }, { "id": "farmers-carry", "ref": "farmers-carry" }, { "id": "sandbag-lunges", "ref": "sandbag-lunges" }, { "id": "wall-balls", "ref": "wall-balls" } ] }, "answers": [ { "field": { "id": "athlete-name" }, "text": "Peter" }, { "field": { "id": "ski-erg" }, "number": 4 }, { "field": { "id": "sled-push" }, "number": 7 }, { "field": { "id": "sled-pull" }, "number": 2 }, { "field": { "id": "burpee-broad-jumps" }, "number": 7 }, { "field": { "id": "rowing" }, "number": 6 }, { "field": { "id": "farmers-carry" }, "number": 1 }, { "field": { "id": "sandbag-lunges" }, "number": 10 }, { "field": { "id": "wall-balls" }, "number": 3 } ] } } '